# Generated by Django 5.2 on 2025-04-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_category_recipe_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="status",
            field=models.CharField(
                choices=[
                    ("review", "Review"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                max_length=255,
            ),
        ),
    ]
